SEED_TITLES = [
    {"title": "The Expanse", "kind": "show", "release_year": 2015, "genre": "Sci-Fi"},
    {"title": "Dune: Part Two", "kind": "movie", "release_year": 2024, "genre": "Sci-Fi"},
    {"title": "Severance", "kind": "show", "release_year": 2022, "genre": "Thriller"},
    {"title": "Everything Everywhere All at Once", "kind": "movie", "release_year": 2022, "genre": "Comedy"},
    {"title": "Andor", "kind": "show", "release_year": 2022, "genre": "Sci-Fi"},
    {"title": "Oppenheimer", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "The Bear", "kind": "show", "release_year": 2022, "genre": "Drama"},
    {"title": "Past Lives", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "Shogun", "kind": "show", "release_year": 2024, "genre": "Drama"},
    {"title": "Poor Things", "kind": "movie", "release_year": 2023, "genre": "Comedy"},
    {"title": "Slow Horses", "kind": "show", "release_year": 2022, "genre": "Thriller"},
    {"title": "Anatomy of a Fall", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "Fargo", "kind": "show", "release_year": 2014, "genre": "Thriller"},
    {"title": "The Holdovers", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "Reservation Dogs", "kind": "show", "release_year": 2021, "genre": "Comedy"},
    {"title": "Killers of the Flower Moon", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "Pachinko", "kind": "show", "release_year": 2022, "genre": "Drama"},
    {"title": "The Zone of Interest", "kind": "movie", "release_year": 2023, "genre": "Drama"},
    {"title": "Beef", "kind": "show", "release_year": 2023, "genre": "Drama"},
    {"title": "Aftersun", "kind": "movie", "release_year": 2022, "genre": "Drama"},
]
